### ISSUE TITLE
[FEATURE] Angles chams

### ISSUE THREAD

**Issue by W0lweR** [NimbusProjects/Nimbus#15]
Good day.
So i wanna ask you to add chams to fake angles like this:
![w7UN3np](https://user-images.githubusercontent.com/42712257/78387237-a8510a80-75e7-11ea-9e5d-4b75da5ac3f9.jpg)
Really wanna see this in future. I cant see my real angles and because of it LegitAA is very hard-to-use. 

Hope, you liked my idea)) 
Please, add it <3

**Comment by acuifex** [comment]
it's hard to implement properly. at least we need to create and maintain animstate.

**Comment by acuifex** [comment]
... and for legitaa use "aa debug" or whatever zedespook named it
