### ISSUE TITLE
Random crashes after update

### ISSUE THREAD

**Issue by TheAifam5** [NimbusProjects/Nimbus#16]
Crashes with a callstack:
Aimbot::CreateMove -> GetClosestPlayerAndSpot -> lockedOn->GetDormant()

Throws something about NULL, maybe vtable indexes are shifted. Easy reproducible just by playing MM or any server, will crash in a matter of minutes (just enable all options like WH, trigger, backtrack etc). After disconnecting and connecting again you will get a crash, or even while playing game.

**Comment by BrainlessDylan** [comment]
i fixed it by turning off all esp but boxes and health

**Comment by TheAifam5** [comment]
Even u disable all everything (factory settings) and you will try to rejoin will crash too.

**Comment by Zedespook** [comment]
> Aimbot::CreateMove -> GetClosestPlayerAndSpot -> lockedOn->GetDormant()

 - Is this a debug log?
 - If not, can you give me a debug log?

It's difficult to find the problem, when so many features listed that can cause the issue, but at least you had some ideas for it. Thank you. I'll work on it. Also, sorry for the late response, my other project is taking up my time. I'm trying my best!

**Comment by TheAifam5** [comment]
Its a callstack where it crashes. It mostly happens on the replay when you dead on Deathmatch, but completely randomly while in Matchmaking.

GetDormant function calls the vtable, lockedOn is not NULL, it crashes directly while executing the vtable function.

**Comment by Zedespook** [comment]
Which file?

**Comment by Zedespook** [comment]
Might have fixed it my dev branch now, can you test?
